services:
  testnet4:
    build:
      context: .
      dockerfile: Dockerfile
    image: keychainmdip/bitcoin-core
    container_name: testnet4
    volumes:
      - ./data:/root/.bitcoin
    ports:
      - "48333:48333"
      - "48332:48332"
